
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: ⬇️ Checkout do Código
      uses: actions/checkout@v4

    - name: 🐍 Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: ⚙️ Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        # Assumindo que você tem um arquivo requirements.txt
        pip install -r requirements.txt 
        # Instalar django, pillow, etc. se não estiverem no requirements.txt

    - name: ✅ Rodar Testes do Django
      # Você precisará ter testes em beats/playlist/tests.py
      run: python manage.py test
      env:
        # Usar variáveis de ambiente para a chave secreta
        SECRET_KEY: ${{ secrets.SECRET_KEY }} 
        DEBUG: "False"

  # ==================================
  # 2. CD (ENTREGA CONTÍNUA/DEPLOY)
  # ==================================
  deploy:
    # Só executa se a etapa 'ci' for bem-sucedida
    needs: ci
    runs-on: ubuntu-latest
    
    # Só executa para pushes no branch principal
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: ⬇️ Checkout do Código
        uses: actions/checkout@v4
      
      # ----------------------------------------------------
      # Exemplo de Deploy 1: SSH (Servidor Privado)
      # ----------------------------------------------------
      - name: 🚀 Deploy via SSH (Recomendado para VPS)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}              # IP do seu servidor
          username: ${{ secrets.SSH_USERNAME }}      # Usuário SSH (ex: ubuntu)
          key: ${{ secrets.SSH_PRIVATE_KEY }}        # Chave SSH privada
          script: |
            # Comandos de deploy no seu servidor remoto
            cd /caminho/do/seu/projeto/no/servidor
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py collectstatic --noinput
            python manage.py migrate
            sudo systemctl restart gunicorn # Reinicia o servidor de produção (ex: Gunicorn/uWSGI)
