# Generated by Django 5.2.6 on 2025-09-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='playlist',
            name='musicas',
            field=models.ManyToManyField(related_name='playlists', to='playlist.musica'),
        ),
    ]
